"""AXON Export Module

Creates a portable model bundle after gates pass.

Target structure:
outputs/model_bundles/<model_id>/
  model.pkl
  feature_spec.yaml
  preprocess.py
  infer.py
  model_card.json
  runtime.txt
  checksum.sha256
"""
from __future__ import annotations

from pathlib import Path
from typing import Dict, Any, Optional
import json
import yaml
import shutil
import hashlib
from datetime import datetime

from .utils import load_config, ensure_dir


def _read_json(p: Path) -> Dict[str, Any]:
    try:
        return json.loads(p.read_text())
    except Exception:
        return {}


def _find_latest_bt_for_model(model_name: str) -> Optional[Path]:
    metrics_dir = Path("outputs/metrics")
    if not metrics_dir.exists():
        return None
    candidates = sorted(metrics_dir.glob(f"BT_{model_name}_*.json"))
    return candidates[-1] if candidates else None


def _sha256_of_file(file_path: Path) -> str:
    h = hashlib.sha256()
    with open(file_path, 'rb') as f:
        for chunk in iter(lambda: f.read(8192), b''):
            h.update(chunk)
    return h.hexdigest()


def _write_feature_spec(target_dir: Path, feature_names: list, target_col: str) -> None:
    spec = {
        'features': feature_names,
        'target': target_col,
        'generated_at': datetime.utcnow().isoformat() + 'Z'
    }
    (target_dir / 'feature_spec.yaml').write_text(yaml.safe_dump(spec, sort_keys=False))


def _write_preprocess_py(target_dir: Path, feature_names: list, target_col: str) -> None:
    code = f'''# Auto-generated by AXON export
# Minimal preprocessing: select expected features and drop target/timestamp.
from typing import List
import pandas as pd

FEATURES: List[str] = {feature_names!r}
TARGET: str = {target_col!r}


def transform(df: pd.DataFrame) -> pd.DataFrame:
    cols = [c for c in FEATURES if c in df.columns]
    X = df[cols].copy()
    return X
'''
    (target_dir / 'preprocess.py').write_text(code)


def _write_infer_py(target_dir: Path) -> None:
    code = '''# Auto-generated by AXON export
from pathlib import Path
import pickle
import pandas as pd
from preprocess import transform

_model = None

def load(model_path: str | Path = 'model.pkl'):
    global _model
    with open(model_path, 'rb') as f:
        _model = pickle.load(f)
    return _model

def predict_proba(df: pd.DataFrame):
    if _model is None:
        load('model.pkl')
    X = transform(df)
    if hasattr(_model, 'predict_proba'):
        return _model.predict_proba(X)[:, 1]
    return _model.predict(X)
'''
    (target_dir / 'infer.py').write_text(code)


def _write_runtime_txt(target_dir: Path) -> None:
    runtime = """python>=3.11
pandas>=1.5.0
numpy>=1.24.0
scikit-learn>=1.3.0
lightgbm>=4.0.0
pyarrow>=10.0.0
"""
    (target_dir / 'runtime.txt').write_text(runtime)


def _write_model_card(target_dir: Path, model_id: str, meta: Dict[str, Any], bt_metrics: Dict[str, Any]) -> None:
    card = {
        'model_id': model_id,
        'created_at': datetime.utcnow().isoformat() + 'Z',
        'training': {
            'timestamp': meta.get('timestamp'),
            'metrics': meta.get('metrics', {}),
            'features': meta.get('feature_names', []),
        },
        'backtest': bt_metrics,
        'source': 'AXON Lab',
        'repro': {
            'config_snapshot': meta.get('config', {}),
            'artifact_path': meta.get('model_path'),
        },
    }
    (target_dir / 'model_card.json').write_text(json.dumps(card, indent=2))


def export_model_bundle(config: Optional[Dict[str, Any]] = None) -> Optional[Path]:
    """Export the latest promoted model into a portable bundle.

    If DECISION.json indicates pass==True, resolves the candidate model name,
    finds latest BT metrics for that model to obtain the exact artifact path,
    and builds the bundle under outputs/model_bundles/<model_id>/.
    """
    cfg = config or load_config()

    decision_path = Path('outputs/metrics/DECISION.json')
    if not decision_path.exists():
        return None
    decision = _read_json(decision_path)
    if not decision or not decision.get('pass'):
        return None

    model_name = decision.get('candidate')
    if not model_name:
        return None

    # Find latest BT metrics for this model to resolve artifact path
    bt_file = _find_latest_bt_for_model(model_name)
    if not bt_file:
        return None
    bt_data = _read_json(bt_file)
    bt_metrics = bt_data.get('metrics', {})
    model_path_str = bt_metrics.get('model_path')
    if not model_path_str:
        return None

    model_path = Path(model_path_str)
    if not model_path.exists():
        return None

    model_id = model_path.stem  # e.g., lightgbm_20250831_153547
    metadata_path = model_path.with_name(f"{model_id}_metadata.json")
    meta = _read_json(metadata_path) if metadata_path.exists() else {}

    feature_names = meta.get('feature_names', [])
    target_col = cfg.get('target', 'y')

    # Prepare target directory
    bundle_dir = Path(f"outputs/model_bundles/{model_id}")
    ensure_dir(str(bundle_dir))

    # Copy model
    shutil.copy2(model_path, bundle_dir / 'model.pkl')

    # Write specs and helpers
    _write_feature_spec(bundle_dir, feature_names, target_col)
    _write_preprocess_py(bundle_dir, feature_names, target_col)
    _write_infer_py(bundle_dir)
    _write_runtime_txt(bundle_dir)
    _write_model_card(bundle_dir, model_id, meta, bt_metrics)

    # Write checksum for model file
    checksum = _sha256_of_file(bundle_dir / 'model.pkl')
    (bundle_dir / 'checksum.sha256').write_text(f"{checksum}  model.pkl\n")

    print(f"📦 Model bundle exported to {bundle_dir}")
    return bundle_dir


if __name__ == "__main__":
    export_model_bundle()